config/routes.rb
Rails.application.routes.draw do

	get "main/home" => 'main#home', :as => :home

  #root 'main#home'

  devise_for :users, path: 'users'
	# eg. http://localhost:3000/users/sign_in
	devise_for :admins, path: 'admins'
	# eg. http://localhost:3000/admins/sign_in


	#si un administrador esta autenticado
  authenticated :admin do
    root 'main#homeAdmin'
  end

  #si un user esta autenticado
  authenticated :user do
  	root 'main#homeUser'
  end

  #si un user  NO esta autenticado
  unauthenticated :user do
    root 'main#userUnregistered'
  end

  #si un administrador NO esta autenticado
  unauthenticated :admin do
    root 'main#adminUnregistered'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout :set_layout
  before_action :configurar_strong_params, if: :devise_controller?


  protected
  	def set_layout
  		
	  	"application"
	  	
	end

  def configurar_strong_params
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :firs_last_name, :second_last_name])
  end


end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def home
  end

  def homeAdmin
  	redirect_to home_path
  end

  def homeUser
  	redirect_to home_path
  end

  def userUnregistered
  	redirect_to new_user_registration_path
  end

  def adminUnregistered
  	redirect_to new_admin_registration_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GamificationFaurecia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  	<!--  Barra de navegacion de los usuarios  -->    
    <% if user_signed_in? %>  
          <%= render "partials/navUser" %>
        <main class="mdl-layout__content">
          <div class="page-content">  <%= yield %> </div>
        </main>

    <% end %> 


    <!--  Barra de navegacion de los administradores  -->    
    <% if admin_signed_in? %>  
          <%= render "partials/navAdmin" %>
        <main class="mdl-layout__content">
          <div class="page-content">  <%= yield %> </div>
        </main>

    <% end %> 



    <% if !current_user and !current_admin %>

      <%= yield %>

    <% end %>


  </body>
</html>

app/views/main/home.html.erb
<h1>Main#home</h1>
<p>Find me in app/views/main/home.html.erb</p>
<h4>HOLA MUNDO</h4>


<li>  <%= link_to "Sign out" , destroy_user_session_path, method: :delete ,class:"black-text"%>   </li>


<% if current_admin %>
	<h4>I am admin</h4>
<% end %>

<% if current_user %>
	<h4>I am user</h4>
<% end %>


<%= instant_hangout topic: 'Asesoria de Matemáticas' %>


<%= instant_hangout hangout_type: 'moderated' %>

app/views/partials/_navAdmin.html.erb
<!-- Esta es la barra de navegación del estudiante: vacantes, editar perfil y cerrar sesión -->
<nav>
    <div class="nav-wrapper">


      <a class="brand-logo"> <%=image_tag('faurecia_blanco.png',height:"22", width:"140", alt:"Faurecia") %> </a>

      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>

      <!-- Menu escritorio  -->
      <ul class="right hide-on-med-and-down">
        <li>
            <%= link_to "admin" , root_path, class:"white-text right-space"%>
        </li>
        <li>  <%= link_to "Sign out" , destroy_user_session_path, method: :delete ,class:"white-text"%>   </li>
      </ul>

      <!-- Menu para telefono  -->
      <ul class="side-nav" id="mobile-demo">
        <li class = "logo"> <h4 class="pink-text text-center">Menu</h4> </li>
        
        <li>
            <%= link_to "prueba" , root_path, class:"white-text right-space"%>
        </li>
        <li>  <%= link_to "Sign out" , destroy_user_session_path, method: :delete ,class:"white-text"%>   </li>

        
      </ul>


    </div>

 </nav>

app/views/partials/_navUser.html.erb
<!-- Esta es la barra de navegación del estudiante: vacantes, editar perfil y cerrar sesión -->
<nav>
    <div class="nav-wrapper">


      <a class="brand-logo"> <%=image_tag('faurecia_blanco.png',height:"22", width:"140", alt:"Faurecia") %> </a>

      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>

      <!-- Menu escritorio  -->
      <ul class="right hide-on-med-and-down">
        <li>
            <%= link_to "instrucciones" , root_path, class:"white-text right-space"%>
        </li>

        <li>
            <%= link_to "canjear puntos" , root_path, class:"white-text right-space"%>
        </li>

        <li>
            <%= link_to "rating" , root_path, class:"white-text right-space"%>
        </li>

        <li>
            <%= link_to "recomendados" , root_path, class:"white-text right-space"%>
        </li>

        <li>
            <%= link_to "nuevo recomendado" , root_path, class:"white-text right-space"%>
        </li>

        <li>  <%= link_to "Sign out" , destroy_user_session_path, method: :delete ,class:"white-text"%>   </li>
      </ul>

      <!-- Menu para telefono  -->
      <ul class="side-nav" id="mobile-demo">
        <li class = "logo"> <h4 class="pink-text text-center">Menu</h4> </li>
        
        <li>
            <%= link_to "prueba" , root_path, class:"white-text right-space"%>
        </li>
        <li>  <%= link_to "Sign out" , destroy_user_session_path, method: :delete ,class:"white-text"%>   </li>


      </ul>


    </div>

 </nav>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "I have a count", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>